apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: test
spec:
  replicas: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxUnavailable: "25%"
    type: RollingUpdate
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: aliyun-hub
      containers:
        - name: web
          image: hub.xxx.com/app/web:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          command:
            - python
          args:
            - manage.py
            - runserver
            - 0.0.0.0:8000
          ports:
            - name: work
              containerPort: 8000
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: test
  labels:
    srv: web
spec:
  type: ClusterIP
  ports:
    - name: web
      targetPort: 8000
      port: 8000
      protocol: TCP
  #spec:
  #  type: NodePort
  #  ports:
  #    - name: work
  #      targetPort: 8000
  #      port: 8000
  #      protocol: TCP
  #      nodePort: 31134
  selector:
    app: web